@extends('dashboard')

@section('content')
	@if(Auth::user()->level == 'admin')
		@if($page)
			@switch($page)
				@case('dashboard')
					@include('layouts.defaultcontent')
				@break
				@case('users')
					@include('dash-admin.users')
				@break
				@case('siswa')
					@include('dash-admin.siswa')
				@break
				@case('rombel')
					@include('dash-admin.rombel')
				@break
				@case('mapel')
					@include('dash-admin.mapel')
				@break
				@case('jadwal')
					@include('dash-admin.jadwal')
				@break
				@case('sekolah')
					@include('dash-admin.sekolah')
				@break
				@case('pengaturan')
					@include('dash-admin.pengaturan')
				@break
			@endswitch
		@endif
	@endif
@endsection
